add unittest to the mix

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -14,6 +14,10 @@ if ! type mktemp 2> /dev/null > /dev/null; then
     exit 1
 fi
 
+# ******************************************************************************
+# * Stage 1: Linting                                                           *
+# ******************************************************************************
+
 # Check that PyLint is installed ...
 if type pylint 2> /dev/null > /dev/null; then
     # Check that there is a PyLint configuration file ...
@@ -77,5 +81,21 @@ if type shellcheck 2> /dev/null > /dev/null; then
 
         # Clean up ...
         rm "${t}"
+    fi
+fi
+
+# ******************************************************************************
+# * Stage 2: Testing                                                           *
+# ******************************************************************************
+
+# Check that Python is installed ...
+if type python 2> /dev/null > /dev/null; then
+    # Check that there is a Python script for the "unittest" module ...
+    if [ -f unitTests.py ]; then
+        # Run Python ...
+        if ! python -m unittest unitTests.py; then
+            echo "ERROR: Python failed." >&2
+            exit 1
+        fi
     fi
 fi
