catch file names with spaces in them

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -28,6 +28,12 @@ if [ -f .pylint.ini ]; then
     t="$(mktemp)"
     git ls-files "*.py" | sort > "${t}"
 
+    # Check that no *.py files have a space in their file name ...
+    if ! grep -F " " "${t}" 2> /dev/null > /dev/null; then
+        echo "ERROR: There is a *.py file which has a space in its file name." >&2
+        exit 1
+    fi
+
     # Count how many *.py files there are ...
     n="$(wc -l "${t}" | cut -f 2 -w)"                                           # [#]
 
@@ -44,6 +50,12 @@ if [ -f .shellcheckrc ]; then
     # Save a list of all the *.sh files there are in the repository ...
     t="$(mktemp)"
     git ls-files "*.sh" | sort > "${t}"
+
+    # Check that no *.sh files have a space in their file name ...
+    if ! grep -F " " "${t}" 2> /dev/null > /dev/null; then
+        echo "ERROR: There is a *.sh file which has a space in its file name." >&2
+        exit 1
+    fi
 
     # Count how many *.sh files there are ...
     n="$(wc -l "${t}" | cut -f 2 -w)"                                           # [#]
