missing binaries is no longer a failure

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -13,63 +13,63 @@ if ! type mktemp 2> /dev/null > /dev/null; then
     echo "ERROR: \"mktemp\" is not installed." >&2
     exit 1
 fi
-if ! type pylint 2> /dev/null > /dev/null; then
-    echo "ERROR: \"pylint\" is not installed." >&2
-    exit 1
-fi
-if ! type shellcheck 2> /dev/null > /dev/null; then
-    echo "ERROR: \"shellcheck\" is not installed." >&2
-    exit 1
-fi
 
-# Check that there is a PyLint configuration file ...
-if [ -f .pylint.ini ]; then
-    # Save a list of all the *.py files there are in the repository ...
-    t="$(mktemp)"
-    git ls-files "*.py" | sort > "${t}"
+# Check that PyLint is installed ...
+if type pylint 2> /dev/null > /dev/null; then
+    # Check that there is a PyLint configuration file ...
+    if [ -f .pylint.ini ]; then
+        # Save a list of all the *.py files there are in the repository ...
+        t="$(mktemp)"
+        git ls-files "*.py" | sort > "${t}"
 
-    # Check that no *.py files have a space in their file name ...
-    if grep -F " " "${t}" 2> /dev/null > /dev/null; then
-        echo "ERROR: There is a *.py file which has a space in its file name." >&2
-        exit 1
-    fi
-
-    # Count how many *.py files there are ...
-    n="$(wc -l "${t}" | cut -f 2 -w)"                                           # [#]
-
-    # Check that there are *.py files in the repository ...
-    if [ "${n}" -gt 0 ]; then
-        # Run PyLint ...
-        echo "Running PyLint on ${n} *.py files ..."
-        if ! pylint --rcfile=.pylint.ini --errors-only $(cat "${t}"); then
-            echo "ERROR: PyLint failed." >&2
+        # Check that no *.py files have a space in their file name ...
+        # NOTE: This would break the upcoming "cat" command.
+        if grep -F " " "${t}"; then
+            echo "ERROR: There is a *.py file which has a space in its file name." >&2
             exit 1
+        fi
+
+        # Count how many *.py files there are ...
+        n="$(wc -l "${t}" | cut -f 2 -w)"                                       # [#]
+
+        # Check that there are *.py files in the repository ...
+        if [ "${n}" -gt 0 ]; then
+            # Run PyLint ...
+            echo "Running PyLint on ${n} *.py files ..."
+            if ! pylint --rcfile=.pylint.ini --errors-only $(cat "${t}"); then
+                echo "ERROR: PyLint failed." >&2
+                exit 1
+            fi
         fi
     fi
 fi
 
-# Check that there is a ShellCheck configuration file ...
-if [ -f .shellcheckrc ]; then
-    # Save a list of all the *.sh files there are in the repository ...
-    t="$(mktemp)"
-    git ls-files "*.sh" | sort > "${t}"
+# Check that ShellCheck is installed ...
+if type shellcheck 2> /dev/null > /dev/null; then
+    # Check that there is a ShellCheck configuration file ...
+    if [ -f .shellcheckrc ]; then
+        # Save a list of all the *.sh files there are in the repository ...
+        t="$(mktemp)"
+        git ls-files "*.sh" | sort > "${t}"
 
-    # Check that no *.sh files have a space in their file name ...
-    if grep -F " " "${t}" 2> /dev/null > /dev/null; then
-        echo "ERROR: There is a *.sh file which has a space in its file name." >&2
-        exit 1
-    fi
-
-    # Count how many *.sh files there are ...
-    n="$(wc -l "${t}" | cut -f 2 -w)"                                           # [#]
-
-    # Check that there are *.sh files in the repository ...
-    if [ "${n}" -gt 0 ]; then
-        # Run ShellCheck ...
-        echo "Running ShellCheck on ${n} *.sh files ..."
-        if ! shellcheck --severity=error $(cat "${t}"); then
-            echo "ERROR: ShellCheck failed." >&2
+        # Check that no *.sh files have a space in their file name ...
+        # NOTE: This would break the upcoming "cat" command.
+        if grep -F " " "${t}"; then
+            echo "ERROR: There is a *.sh file which has a space in its file name." >&2
             exit 1
+        fi
+
+        # Count how many *.sh files there are ...
+        n="$(wc -l "${t}" | cut -f 2 -w)"                                       # [#]
+
+        # Check that there are *.sh files in the repository ...
+        if [ "${n}" -gt 0 ]; then
+            # Run ShellCheck ...
+            echo "Running ShellCheck on ${n} *.sh files ..."
+            if ! shellcheck --severity=error $(cat "${t}"); then
+                echo "ERROR: ShellCheck failed." >&2
+                exit 1
+            fi
         fi
     fi
 fi
